//! Exact math parity vs fogleman/primitive (CORE-1 correctness oracle).
//!
//! Asserts the Rust port reproduces fogleman's unexported pixel math **bit-for-bit** on a
//! committed fixture (`tests/fixtures/parity_fogleman.json`, generated by
//! `go_primitive/primitive/parity_dump_test.go`). This is a stronger guarantee than an
//! SSIM-vs-reference image: the RNG-independent math is checked to exact equality, which a
//! cross-language random-seed comparison never could (fogleman seeds with wall-clock time).

use primitive_core::canvas::Canvas;
use primitive_core::color::compute_color;
use primitive_core::draw::{copy_lines, draw_lines};
use primitive_core::raster::{crop_scanlines, rasterize_triangle, Scanline};
use primitive_core::score::{difference_full, difference_partial, sse_full};
use serde_json::Value;

fn build_target(w: usize, h: usize) -> Canvas {
    let mut c = Canvas::new(w, h);
    for y in 0..h {
        for x in 0..w {
            let i = c.pix_offset(x, y);
            c.pix[i] = ((x * 7 + y * 13) & 255) as u8;
            c.pix[i + 1] = ((x * 3 + y * 5) & 255) as u8;
            c.pix[i + 2] = ((x + y * 2) & 255) as u8;
            c.pix[i + 3] = 255;
        }
    }
    c
}

#[test]
fn fogleman_math_parity_bit_exact() {
    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/parity_fogleman.json"
    ))
    .expect("parity fixture present (regenerate with `go test -run TestDumpParityFixture`)");
    let fx: Value = serde_json::from_str(&raw).unwrap();

    let w = fx["width"].as_u64().unwrap() as usize;
    let h = fx["height"].as_u64().unwrap() as usize;
    let alpha = fx["alpha"].as_i64().unwrap() as i32;
    let cur = &fx["current"];
    let (cr, cg, cb) = (
        cur[0].as_u64().unwrap() as u8,
        cur[1].as_u64().unwrap() as u8,
        cur[2].as_u64().unwrap() as u8,
    );

    let target = build_target(w, h);
    let current = Canvas::filled(w, h, cr, cg, cb);

    // The integer SSE is the bitwise-parity contract (§6.6). The final `sqrt(SSE/N)/255`
    // normalization is correctly-rounded on both sides but may differ by ≤1 ULP across
    // libm implementations — assert it to a tight epsilon, not bit-for-bit.
    let approx = |a: f64, b: f64, what: &str| {
        assert!((a - b).abs() <= 1e-9, "{what}: {a} vs fogleman {b}");
    };

    let score_current = difference_full(&target, &current);
    approx(
        score_current,
        fx["difference_full_current"].as_f64().unwrap(),
        "differenceFull(target, current)",
    );

    for case in fx["cases"].as_array().unwrap() {
        let tri = &case["tri"];
        let t: Vec<i32> = (0..6).map(|k| tri[k].as_i64().unwrap() as i32).collect();

        // --- rasterization parity ---
        let mut lines = Vec::new();
        rasterize_triangle(t[0], t[1], t[2], t[3], t[4], t[5], &mut lines);
        crop_scanlines(&mut lines, w as i32, h as i32);

        let expected_sl = case["scanlines"].as_array().unwrap();
        assert_eq!(lines.len(), expected_sl.len(), "scanline count for {t:?}");
        for (got, want) in lines.iter().zip(expected_sl) {
            let exp = Scanline {
                y: want[0].as_i64().unwrap() as i32,
                x1: want[1].as_i64().unwrap() as i32,
                x2: want[2].as_i64().unwrap() as i32,
                alpha: want[3].as_u64().unwrap() as u32,
            };
            assert_eq!(*got, exp, "scanline mismatch for {t:?}");
        }

        // --- closed-form color parity ---
        let color = compute_color(&target, &current, &lines, alpha);
        let ec = &case["color"];
        assert_eq!(
            [color.r, color.g, color.b, color.a],
            [
                ec[0].as_i64().unwrap() as i32,
                ec[1].as_i64().unwrap() as i32,
                ec[2].as_i64().unwrap() as i32,
                ec[3].as_i64().unwrap() as i32
            ],
            "computeColor mismatch for {t:?}"
        );

        // --- compositing parity ---
        let mut after = current.clone();
        copy_lines(&mut after, &current, &lines);
        draw_lines(&mut after, color, &lines);
        for cov in case["covered"].as_array().unwrap() {
            let i = cov[0].as_u64().unwrap() as usize;
            assert_eq!(
                [
                    after.pix[i],
                    after.pix[i + 1],
                    after.pix[i + 2],
                    after.pix[i + 3]
                ],
                [
                    cov[1].as_u64().unwrap() as u8,
                    cov[2].as_u64().unwrap() as u8,
                    cov[3].as_u64().unwrap() as u8,
                    cov[4].as_u64().unwrap() as u8
                ],
                "drawLines composited pixel mismatch at offset {i} for {t:?}"
            );
        }

        // --- scoring parity (integer SSE exact; normalized scores bit-exact) ---
        assert_eq!(
            sse_full(&target, &after),
            case["sse_after"].as_u64().unwrap(),
            "integer SSE mismatch for {t:?}"
        );
        approx(
            difference_full(&target, &after),
            case["difference_full_after"].as_f64().unwrap(),
            &format!("differenceFull(after) for {t:?}"),
        );
        let partial = difference_partial(&target, &current, &after, score_current, &lines);
        approx(
            partial,
            case["difference_partial"].as_f64().unwrap(),
            &format!("differencePartial for {t:?}"),
        );
    }
}
